### PR TITLE
Sending json the right way. Fixes #38

### LINKED ISSUE #38: malt is serving json and source files as xml
Upon loading a trace I'm seeing in the browser console:

```
XML Parsing Error: syntax error
Location: http://kaby:8080/flat.json
Line Number 1, Column 1: flat.json:1:1
XML Parsing Error: syntax error
Location: http://kaby:8080/stacks.json?func=
Line Number 1, Column 1: stacks.json:1:1
XML Parsing Error: syntax error
Location: http://kaby:8080/stacks.json?func=rav1e%3A%3Aencoder%3A%3Aencode_tx_block
Line Number 1, Column 1:
stacks.json:1:1
```

And in the network tab indeed I see the type marked as xml.

Tested with firefox 67.0b15 and chrome and the behavior seems the same.

### PR DESCRIPTION
**Pull request by ffissore**
This PR includes fixes to #38. Please be aware that I've *not* run the code, as I'm not a malt user, so please test it or take this PR as a starting point.

### CODE REVIEW

**Comment by ffissore** [comment]
As a a side note, it's better to avoid JSON formatting on the server side. If you want to show pretty printed json on the browser, use a plugin or a recent version of firefox; if you want it on the terminal, use https://crates.io/crates/jsonpp

**Comment by svalat** [comment]
Hi, sorry, just see I first merged another same PR made by another contributor for the same fix but thanks very much for the fix. That's a pain both made it at exact same time.

**Comment by svalat** [comment]
https://github.com/memtt/malt/pull/40

**Comment by ffissore** [comment]
No worries, luzero took my commit and added his, so I still made my part in contributing to malt
Keep up the good work

**Pull request closed without merging**
